components_manager:
    task_processors:                  # Task processor is an executor for coroutine tasks

        main-task-processor:          # Make a task processor for CPU-bound couroutine tasks.
            worker_threads: $worker-threads         # Process tasks in 4 threads.

        fs-task-processor:            # Make a separate task processor for filesystem bound tasks.
            worker_threads: $worker-fs-threads

    default_task_processor: main-task-processor

    components:                       # Configuring components that were registered via component_list
        server:
            listener:                 # configuring the main listening socket...
                port: $server-port            # ...to listen on this port and...
                task_processor: main-task-processor    # ...process incoming requests on this task processor.
        logging:
            fs-task-processor: fs-task-processor
            loggers:
                default:
                    file_path: '@stderr'
                    level: $logger-level
                    overflow_behavior: discard  # Drop logs if the system is too busy to write them down.

        # Dynamic config options. Cache is disabled, updates are disabled.
        dynamic-config:
            # For most of userver dynamic configs, defaults are used, some are overridden here.
            # See userver "dynamic config" docs for what configs exist.
            defaults:
                HTTP_CLIENT_CONNECTION_POOL_SIZE: 1000
                POSTGRES_DEFAULT_COMMAND_CONTROL:
                    network_timeout_ms: 750
                    statement_timeout_ms: 500

        testsuite-support: {}

        http-client:
            load-enabled: $is-testing
            fs-task-processor: fs-task-processor

        tests-control:
            load-enabled: $is-testing
            path: /tests/{action}
            method: POST
            task_processor: main-task-processor
        handler-ping:
            path: /ping
            method: GET
            task_processor: main-task-processor
            throttling_enabled: false
            url_trailing_slash: strict-match
        
        handler-user-name-update:
            path: /v1/update/user_name
            method: PUT
            task_processor: main-task-processor

        handler-user-type-update:
            path: /v1/user/{id}/type/change
            method: PUT
            task_processor: main-task-processor

        handler-register-user:
            path: /register
            method: POST
            task_processor: main-task-processor

        handler-login-user:
            path: /login
            method: POST
            task_processor: main-task-processor

        handler-v1-course-create:
            path: /v1/course/create
            method: POST
            task_processor: main-task-processor   
        
        handler-v1-user-add-to-course:
            path: /v1/user/add/to_course/{id}
            method: POST
            task_processor: main-task-processor

        handler-v1-user-leave-course:
            path: /v1/user/leave/course/{id}
            method: DELETE
            task_processor: main-task-processor
            
        # handler-v1-user-by-id-add-to-course-by-id:
        #     path: /v1/user/{user_id}/add/to_course/{course_id}
        #     method: POST
        #     task_processor: main-task-processor

        handler-v1-get-courses:
            path: /v1/courses
            method: GET
            task_processor: main-task-processor

        # handler-v1-course:
        #     path: /v1/course/{id}
        #     method: GET,PUT,DELETE
        #     task_processor: main-task-processor

        # handler-v1-course-get-students:
        #     path: /v1/course/{id}/students
        #     method: GET
        #     task_processor: main-task-processor

        # handler-v1-course-get-teachers:
        #     path: /v1/course/{id}/teachers
        #     method: GET
        #     task_processor: main-task-processor

        # handler-v1-course-get-admins:
        #     path: /v1/course/{id}/admins
        #     method: GET
        #     task_processor: main-task-processor

        # handler-v1-course-get-lessons:
        #     path: /v1/course/{id}/lessons
        #     method: GET
        #     task_processor: main-task-processor
        
        # handler-v1-course-get-lessons-ids:
        #     path: /v1/course/{id}/lessons_ids
        #     method: GET
        #     task_processor: main-task-processor    

        # handler-v1-course-get-materials:
        #     path: /v1/course/{id}/materials
        #     method: GET
        #     task_processor: main-task-processor    

        # handler-v1-course-get-tasks:
        #     path: /v1/course/{id}/tasks
        #     method: GET
        #     task_processor: main-task-processor

        # handler-v1-course-add-lesson:
        #     path: /v1/course/{course_id}/add_lesson
        #     method: POST
        #     task_processor: main-task-processor  

        # handler-v1-course-add-material:
        #     path: /v1/course/{course_id}/add_material
        #     method: POST
        #     task_processor: main-task-processor    

        # handler-v1-course-add-task:
        #     path: /v1/course/{course_id}/add_task
        #     method: POST
        #     task_processor: main-task-processor    

        # handler-v1-course-delete-lesson:
        #     path: /v1/course/{course_id}/lesson/{lesson_id}
        #     method: DELETE
        #     task_processor: main-task-processor

        # handler-v1-course-change-task:
        #     path: /v1/course/{course_id}/change_task
        #     method: PUT 
        #     task_processor: main-task-processor

        # handler-v1-course-inspector:
        #     path: /v1/course/{course_id}/lesson/{lesson_id}/task/{task_id}/student/{student_id}/inspector
        #     method: GET,DELETE
        #     task_processor: main-task-processor

        handler-v1-lesson-create:
            path: /v1/lesson/create
            method: POST
            task_processor: main-task-processor

        handler-v1-get-lessons:
            path: /v1/lessons
            method: GET
            task_processor: main-task-processor

        handler-v1-lesson:
            path: /v1/lesson/{id}
            method: GET,PUT,DELETE
            task_processor: main-task-processor

        # handler-v1-lesson-get-materials:
        #     path: /v1/lesson/{id}/materials
        #     method: GET
        #     task_processor: main-task-processor

        # handler-v1-lesson-get-tasks:
        #     path: /v1/lesson/{id}/tasks
        #     method: GET
        #     task_processor: main-task-processor

        handler-v1-material-create:
            path: /v1/material/create
            method: POST
            task_processor: main-task-processor

        handler-v1-get-materials:
            path: /v1/materials
            method: GET
            task_processor: main-task-processor

        handler-v1-material:
            path: /v1/material/{id}
            method: GET,PUT,DELETE
            task_processor: main-task-processor

        handler-v1-task-create:
            path: /v1/task/create
            method: POST
            task_processor: main-task-processor

        handler-v1-get-tasks:        
            path: /v1/tasks
            method: GET
            task_processor: main-task-processor

        handler-v1-task: 
            path: /v1/task/{id}
            method: GET,PUT,DELETE
            task_processor: main-task-processor

        # handler-v1-set-inspectors:
        #     path: /v1/course/{course_id}/set_inspectors
        #     method: POST
        #     task_processor: main-task-processor

        # handler-v1-set-inspector:
        #     path: /v1/course/{course_id}/set_inspector
        #     method: POST
        #     task_processor: main-task-processor

        # handler-v1-send-solution:
        #     path: /v1/course/{course_id}/send_solution
        #     method: POST
        #     task_processor: main-task-processor    

        lms_service_db_1:
            dbconnection: $dbconnection
            dbconnection#env: DB_CONNECTION
            blocking_task_processor: fs-task-processor
            dns_resolver: async
            sync-start: false
            connlimit_mode: manual

        dns-client:
            fs-task-processor: fs-task-processor
