#include "postgres_components/postgres_components.hpp"

#include "../views/v1/authentication/login/login.hpp"
#include "../views/v1/authentication/register/register.hpp"
#include "../views/v1/catalogs/courses/create_course.hpp"
#include "../views/v1/catalogs/courses/get_courses.hpp"
#include "../views/v1/catalogs/lessons/create_lesson.hpp"
#include "../views/v1/catalogs/lessons/get_lessons.hpp"
#include "../views/v1/catalogs/lessons/lesson_by_id_view.hpp"
#include "../views/v1/users/user_view.hpp"
#include "../views/v1/users/user_type_change_view.hpp"

#include "../views/v1/users/enroll_in_course_view.hpp"
#include "../views/v1/users/leave_course_view.hpp"

#include "../views/v1/catalogs/tasks/create_task.hpp"
#include "../views/v1/catalogs/tasks/get_tasks.hpp"
#include "../views/v1/catalogs/tasks/task_by_id.hpp"
#include "../views/v1/catalogs/materials/create_material.hpp"
#include "../views/v1/catalogs/materials/get_materials.hpp"
#include "../views/v1/catalogs/materials/material_by_id.hpp"
#include "../views/v1/course_administration/add_user_to_course_view.hpp"
