version: "2.3"

services:
    postgres:
        container_name: service-postgres
        image: postgres:12
        environment: &db_env
          POSTGRES_DB: lms_service_db_1
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_EXTENSIONS: uuid-ossp
        ports:
          - 5432:5432
        volumes:
          - ./postgres:/docker-entrypoint-initdb.d
          - ./.pgdata:/var/lib/postgresql/data
        networks:
          - postgres

    lms_service-container:
        image: ghcr.io/userver-framework/ubuntu-22.04-userver-pg:latest
        privileged: true
        environment:
          <<: *db_env
          PREFIX: ${PREFIX:-~/.local}
          CCACHE_DIR: /lms_service/.ccache
          CORES_DIR: /cores
        volumes:
          - .:/lms_service:rw
          - ${TC_CORES_DIR:-./.cores}:/cores:rw
        ports:
          - 8080:8080
        working_dir: /lms_service
        entrypoint:
          - ./tests/run_as_user.sh
        depends_on:
          - postgres
        networks:
          - postgres

networks:
    postgres:
        driver: bridge
