# All the CI stages
stages:
  - analyze # Health check
  - deploy # Upload to prod server

flutter_analyze:
  image: ghcr.io/cirruslabs/flutter
  stage: analyze
  interruptible: true

  before_script:
    - cd frontend
    - flutter clean
    - flutter pub get
  script:
    - dart fix --dry-run
    - dart fix --apply
    - flutter analyze --fatal-warnings --no-fatal-infos
  only:
    refs:
      - merge_requests
  tags:
    - docker-executor

# To run this job you should define the following variables:
# - PROD_USERNAME
# - PROD_HOST

deploy_web:
  stage: deploy
  when: manual
  interruptible: false

  before_script:
    - echo $YC_AUTHORIZED_KEYS > ./authorized_keys
    - chmod 600 ./authorized_keys
    - yc config set service-account-key ./authorized_keys
    - yc container registry configure-docker

  # TODO: move id of registry to the secrets
  script:
    - cd frontend
    - docker build -t frontend .
    - docker tag frontend cr.yandex/crp08k5ngpk2phfn7dum/frontend
    - docker push cr.yandex/crp08k5ngpk2phfn7dum/frontend

    - cd ..
    # Copy actual docker-compose.yaml to prod server
    - scp ./docker-compose.yaml $PROD_USERNAME@$PROD_HOST:/home/$PROD_USERNAME

    # Copy nginx folder to prod server
    - scp -r ./nginx $PROD_USERNAME@$PROD_HOST:/home/$PROD_USERNAME

    # and run docker compose up for new image (sent deploy signal to prod server)
    - ssh $PROD_USERNAME@$PROD_HOST 'docker compose up'

  tags:
    - shell-executor
