default:
  image: ghcr.io/cirruslabs/flutter

# All the CI stages
stages:
  - analyze # Health check
  - deploy # Upload to prod server

flutter_analyze:
  stage: analyze
  interruptible: true

  before_script:
    - cd frontend
    - flutter clean
    - flutter pub get
  script:
    - dart fix --dry-run
    - dart fix --apply
    - flutter analyze --fatal-warnings --no-fatal-infos
  only:
    refs:
      - merge_requests

  tags:
    - flutter_analyze
    - ci

# To run this job you should define the following variables:
# - PROD_USERNAME
# - PROD_HOST
# - SSH_PRIVATE_KEY
deploy_web:
  stage: deploy
  when: manual
  interruptible: false

  # TODO: move id of registry to the secrets
  script:
    - cd frontend
    - docker build -t frontend .
    - docker tag frontend cr.yandex/crp08k5ngpk2phfn7dum/frontend
    - docker push cr.yandex/crp08k5ngpk2phfn7dum/frontend

    - cd ..
    # Copy actual docker-compose.yaml to prod server
    - scp ./docker-compose.yaml $PROD_USERNAME@$PROD_HOST:/home/$PROD_USERNAME

    # and run docker compose up for new image (sent deploy signal to prod server)
    - ssh $PROD_USERNAME@$PROD_HOST 'docker compose up'

  tags:
    - deploy
    - ci
