include:
  # Frontend CI handler
  - local: lms_front/.gitlab-ci.yml
    rules:
      - changes:
          - lms_front/*

  # Backend CI handler
  # - local: yourbackend_entry_dir/.gitlab-ci.yml
  #   rules:
  #     - changes:
  #         - yourbackend_entry_dir/*

# This job basically will not run
# but the GitLab CI will pass its yaml lint without yaml error
#
# This error occured when includes .gitlab-ci.yml without runnable jobs
dummy_job:
  stage: .pre
  script:
    - exit 0
