# For fast fixes of formatting/linter
fix:
	dart fix --apply

# For build model automation 
build_models:
	dart run build_runner build --delete-conflicting-outputs

# For fast generating l10n
l10n:
	flutter gen-l10n
