events {}

# Конфигурация сервера
http {
    server {
        listen 80;
        server_name localhost;  # Можно заменить на домен

        # Расположение статического веб-приложения
        # ? Should we use internal nginx on frontend image?
        # ? and paste proxy_pass http://frontend:port ?
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        # Расположение API
        # location /api/ {
        #     proxy_pass http://backend:5000;  # Имя сервиса и порт, указанные в docker-compose.yml
        #     proxy_set_header Host $host;
        #     proxy_set_header X-Real-IP $remote_addr;
        #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        #     proxy_set_header X-Forwarded-Proto $scheme;
        # }
    }
}